[package]
name = "yespanda"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "yespanda"
path = "src/main.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.9", features = ["v1_5", "v1_6"] }
relm4 = { version = "0.11", features = ["libadwaita"] }
gtk4 = { version = "0.11", features = ["v4_14"] }
gsk4 = { version = "0.11", features = ["v4_14"] }
poppler-rs = { version = "0.26", features = ["v22_2"] }
cairo-rs = { version = "0.22", features = ["pdf"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "1"

[profile.release]
strip = "symbols"
lto = true
opt-level = "s"
